# Generated by Django 5.2.1 on 2025-05-23 23:59

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_achievement_image_alter_achievement_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='achievements'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='achievements'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image_3',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 400], upload_to='achievements'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image_4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 400], upload_to='achievements'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image_5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[400, 400], upload_to='achievements'),
        ),
    ]
